### ISSUE TITLE
latest pufferfish skills version 0.13.0 is not working with simply skills 1.5.0

### ISSUE THREAD

**Issue by szunakabeats** [Sweenus/SimplySkills#102]

**Comment by rinebergc** [comment]
```
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Pufferfish's Skills' (puffish_skills) 0.13.0 with 
	    any version between 0.12.0 (inclusive) and 0.13- (exclusive).
More details:
	 - Mod 'SimplySkills' (simplyskills) 1.5.0+1.20.1 requires any version between 0.12.0 (inclusive) and 0.13- (exclusive)
	   of mod 'Pufferfish's Skills' (puffish_skills), but only the wrong version is present: 0.13.0!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by rinebergc** [comment]
Related to #101

[compatible version range for skills](https://github.com/Sweenus/SimplySkills/pull/101/commits/90196130a97ec4b2f21373c1b78ce28880282be3) not inclusive of 0.13.0
