### ISSUE TITLE
Invalid Accessor Exception

### ISSUE THREAD

**Issue by rinebergc** [Sweenus/SimplySkills#103]
Commit #101 appears to introduce a breaking change.

```
[Render thread/ERROR]:
 Mixin apply for mod simplyskills failed simplyskills.mixins.json:client.SkillsScreenAccessor from mod simplyskills ->
 net.puffish.skillsmod.client.gui.SkillsScreen: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates
 were found matching y:I in net/puffish/skillsmod/client/gui/SkillsScreen for simplyskills.mixins.json:client.SkillsScreenAccessor from
 mod simplyskills->@Accessor[FIELD_GETTER]::getY()I [INJECT Applicator Phase -> simplyskills.mixins.json:client.SkillsScreenAccessor
 from mod simplyskills -> Apply Accessors ->  -> Locate -> simplyskills.mixins.json:client.SkillsScreenAccessor from
 mod simplyskills->@Accessor[FIELD_GETTER]::getY()I]
org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching y:I in net/puffish/skillsmod/client/gui/SkillsScreen for simplyskills.mixins.json:client.SkillsScreenAccessor from mod simplyskills->@Accessor[FIELD_GETTER]::getY()I [INJECT Applicator Phase -> simplyskills.mixins.json:client.SkillsScreenAccessor from mod simplyskills -> Apply Accessors ->  -> Locate -> simplyskills.mixins.json:client.SkillsScreenAccessor from mod simplyskills->@Accessor[FIELD_GETTER]::getY()I]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:519) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:502) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:476) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1411) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1071) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.puffish.skillsmod.main.FabricClientMain.onInitializeClient(FabricClientMain.java:29) ~[puffish_skills-0.13.0-1.20-fabric.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) ~[fabric-loader-0.15.11.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:458) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[1.20.1-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
```

**Comment by Sweenus** [comment]
Have you updated to the latest of both Pufferfish mods, and Simply Skills?

**Comment by rinebergc** [comment]
Resolved
