### ISSUE TITLE
Error after updating Pufferfish's to version 0.9.0

### ISSUE THREAD

**Issue by parzivalvl** [Sweenus/SimplySkills#12]
Please update the mod for the new version of Pufferfish's

![image](https://github.com/Sweenus/SimplySkills/assets/123652924/bfa039a5-c671-440f-a8b4-6b5791040428)

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Pufferfish's Skills' (puffish_skills) 0.9.0 with any version between 0.7.0 (inclusive) and 0.8.0 (inclusive).
Unmet dependency listing:
	 - Mod 'SimplySkills' (simplyskills) 0.19.0+1.20.1 requires any version between 0.7.0 (inclusive) and 0.8.0 (inclusive) of mod 'Pufferfish's Skills' (puffish_skills), but only the wrong version is present: 0.9.0!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Sweenus** [comment]
This will be done when I have time. If you want to use Simply Skills in the interim, dowgrade your Puffish Skills version.
