### ISSUE TITLE
Issue with SimplySkills crashing after updating from version 1.0:

### ISSUE THREAD

**Issue by saintphaenixos** [Sweenus/SimplySkills#73]
Hello all,

First off, I'd like to thank you immensely for the work on Simply Skills, this mod is Simply (Pun intended) Amazing.

------------------

I'm unsure if this is related to #71 but I'm experiencing a similar crash, where I can generally open the game, but when I attempt to open the SimplySkills interface the game crashes, this seems to be the relevant block that pops up during this crash:

```
java.lang.RuntimeException: Shader compilation failed, see log for details
	at me.jellysquid.mods.sodium.client.gl.shader.GlShader.<init>(GlShader.java:34) ~[sodium-fabric-0.5.8+mc1.20.1.jar:?]
	at me.jellysquid.mods.sodium.client.gl.shader.ShaderLoader.loadShader(ShaderLoader.java:22) ~[sodium-fabric-0.5.8+mc1.20.1.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.createShader(ShaderChunkRenderer.java:45) ~[sodium-fabric-0.5.8+mc1.20.1.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.compileProgram(ShaderChunkRenderer.java:36) ~[sodium-fabric-0.5.8+mc1.20.1.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java:72) ~[sodium-fabric-0.5.8+mc1.20.1.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.DefaultChunkRenderer.render(DefaultChunkRenderer.java:48) ~[sodium-fabric-0.5.8+mc1.20.1.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:217) ~[sodium-fabric-0.5.8+mc1.20.1.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:226) ~[sodium-fabric-0.5.8+mc1.20.1.jar:?]
	at net.minecraft.class_761.method_3251(class_761.java:14015) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1253) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:880) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
```

~~It will also crash during generation, but I can't get that to remain reliably the case, so It's hard to give good evidence there for that.~~ This wound up being untrue, I sorta figured out what causes this, I'll explain in the post below.

However the crash for opening the interface _does_ reliably happen everytime.

I'm running Simply Skills 1.3.0 with matching updated libraries, for more detail please see the attached list of mods further down the page.

I'm attaching the log here:
[2024-04-02-7.log](https://github.com/Sweenus/SimplySkills/files/14845462/2024-04-02-7.log)

In addition here is a list of my mods:
[MinecraftModList.txt](https://github.com/Sweenus/SimplySkills/files/14845546/MinecraftModList.txt)

------------------

I'll see if I can test with less mods installed to help narrow this down.

Thank you so much for the work with this, and for any help you're willing to give. :)

**Comment by saintphaenixos** [comment]
I'm still testing, but noticed a strange issue, when freshly installing these mods with Iris.

Iris binds the "K" key to reloading shaders, just as Simply Skills does to open the Skill interface, so there seems to be a conflict, in this default conflict, Iris seems to win and K will reload shaders, but Simply Skills will not open. Resolving the conflict in the keybinds fixes this.

I'm testing this now on my instance with all the mods to see if that remains the case there, and if changing binds fixes it.

-----------------------

Some further testing has shown that pressing K in this configuration with all of my mods will crash it, and when re-opening the world, it will automatically crash. Unless I disable shaders and go back into the world. Whereupon it will load as expected, and I can even re-open my shaders. However pressing K crashes it again.

-----------------------

The K bind seems to be the issue, removing the conflict allows me to open Simply Skills with no issue.

I'm also noting here that I'm running the Distant Horizons/Iris/Bliss Shaders experimental combo which is all very alpha software. I'm going to remove Simply Skills and see if it's Simply Skills's bind that causing the conflict, or if it's unrelated at all.

-----------------------
Last Update:

Alrighty, I've confirmed it, when Simply Skills is removed from this mod-list Pufferfish's skills take over and open fine with a conflicting keybind. It seems to be something about the conflicting keybinds and rendering of Simply Skills during the shader reload (I think Minecraft runs them both concurrently getting the error above. in this circumstance that causes this.

I also figured out that when the K conflict happens, and you crash the game, reloading the game and attempting to load into the same world will then crash before you get into gameplay. Something about this shader reload seems to stick, and it won't even render the game. Disabling the shaders before hopping back in, seems to fix this, of course until K is pressed.
