### ISSUE TITLE
not compatible with the latest pufferfish skills version

### ISSUE THREAD

**Issue by szunakabeats** [Sweenus/SimplySkills#85]

**Comment by FireNneon** [comment]
I also can't use the latest version of pufferfish's skills, This is the error I get when trying to use the latest Version.

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Pufferfish's Skills' (puffish_skills) 0.12.1 with any version between 0.11.6 (inclusive) and 0.11.7 (inclusive).
More details:
	 - Mod 'SimplySkills' (simplyskills) 1.3.2+1.20.1 requires any version between 0.11.6 (inclusive) and 0.11.7 (inclusive) of mod 'Pufferfish's Skills' (puffish_skills), but only the wrong version is present: 0.12.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Sweenus** [comment]
Now compatible
