### ISSUE TITLE
Simple skils dont work

### ISSUE THREAD

**Issue by Tteady** [Sweenus/SimplySkills#94]
simple skills dont work
issue code:
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'SimplySkills' (simplyskills) 1.4.1+1.20.1 with any version that is compatible with:
		 - spell_engine 0.15.0+1.20.1
More details:
	 - Mod 'SimplySkills' (simplyskills) 1.4.1+1.20.1 requires any version between 0.14.0+1.20.1 (inclusive) and 0.15.0+1.20.1 (exclusive) of mod 'Spell Engine' (spell_engine), but only the wrong version is present: 0.15.0+1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
![изображение_2024-06-17_022452700](https://github.com/Sweenus/SimplySkills/assets/119966896/269b23c8-e1cc-4a82-a860-459bfeeea95a)

**Comment by Sweenus** [comment]
Resolved as of version 1.5.0.
