### ISSUE TITLE
Consecration Signature Skill

### ISSUE THREAD

**Issue by Morisillen** [Sweenus/SimplySkills#95]
It doesnt heal or damage anything. I dont know if its caused by another mod since it doesnt give me a crash.

Actually, none of the skills deal damage or heal

**Comment by Snautke** [comment]
I have the same problem that holy skills don't work. I have one of the error reports that I get:

[11:53:41] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2824@53720dd1, suppressing error
java.lang.IllegalArgumentException: Can't find attribute null
	at net.minecraft.class_5132.method_26865(class_5132.java:22) ~[server-intermediary.jar:?]
	at net.minecraft.class_5132.method_26862(class_5132.java:28) ~[server-intermediary.jar:?]
	at net.minecraft.class_5131.method_26852(class_5131.java:76) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_26825(class_1309.java:1904) ~[server-intermediary.jar:?]
	at net.spell_power.api.SpellSchools.lambda$configureAsMagic$0(SpellSchools.java:83) ~[spell_power-0.10.3+1.20.1.jar:?]
	at net.spell_power.api.SpellSchool.getValue(SpellSchool.java:116) ~[spell_power-0.10.3+1.20.1.jar:?]
	at net.spell_power.api.SpellPower.getSpellPower(SpellPower.java:97) ~[spell_power-0.10.3+1.20.1.jar:?]
	at com.spellbladenext.Spellblades.lambda$onInitialize$2(Spellblades.java:301) ~[spellbladenext-1.16.4.jar:?]
	at net.spell_power.api.SpellSchool.getValue(SpellSchool.java:116) ~[spell_power-0.10.3+1.20.1.jar:?]
	at net.spell_power.api.SpellPower.getSpellPower(SpellPower.java:97) ~[spell_power-0.10.3+1.20.1.jar:?]
	at net.sweenus.simplyskills.abilities.ClericAbilities.signatureClericAnointWeaponEffect(ClericAbilities.java:199) ~[simplyskills-1.4.1+1.20.1.jar:?]
	at net.minecraft.class_3222.handler$dmb001$simplyskills$attack(class_3222.java:19806) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_7324(class_3222.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244$1.method_34218(class_3244.java:1610) ~[server-intermediary.jar:?]
	at net.minecraft.class_2824$1.method_34213(class_2824.java:166) ~[server-intermediary.jar:?]
	at net.minecraft.class_2824.method_34209(class_2824.java:66) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_12062(class_3244.java:1571) ~[server-intermediary.jar:?]
	at net.minecraft.class_2824.method_12251(class_2824.java:53) ~[server-intermediary.jar:?]
	at net.minecraft.class_2824.method_11054(class_2824.java:13) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]
[11:53:47] [Server thread/ERROR]: Error executing task on Server
java.lang.IllegalArgumentException: Can't find attribute null
	at net.minecraft.class_5132.method_26865(class_5132.java:22) ~[server-intermediary.jar:?]
	at net.minecraft.class_5132.method_26862(class_5132.java:28) ~[server-intermediary.jar:?]
	at net.minecraft.class_5131.method_26852(class_5131.java:76) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_26825(class_1309.java:1904) ~[server-intermediary.jar:?]
	at net.spell_power.api.SpellSchools.lambda$configureAsMagic$0(SpellSchools.java:83) ~[spell_power-0.10.3+1.20.1.jar:?]
	at net.spell_power.api.SpellSchool.getValue(SpellSchool.java:116) ~[spell_power-0.10.3+1.20.1.jar:?]
	at net.spell_power.api.SpellPower.getSpellPower(SpellPower.java:97) ~[spell_power-0.10.3+1.20.1.jar:?]
	at com.spellbladenext.Spellblades.lambda$onInitialize$2(Spellblades.java:301) ~[spellbladenext-1.16.4.jar:?]
	at net.spell_power.api.SpellSchool.getValue(SpellSchool.java:116) ~[spell_power-0.10.3+1.20.1.jar:?]
	at net.spell_power.api.SpellPower.getSpellPower(SpellPower.java:97) ~[spell_power-0.10.3+1.20.1.jar:?]
	at net.spell_engine.internals.SpellHelper.performSpell(SpellHelper.java:222) ~[spell_engine-0.14.3+1.20.1.jar:?]
	at net.spell_engine.network.ServerNetwork.lambda$initializeHandlers$5(ServerNetwork.java:59) ~[spell_engine-0.14.3+1.20.1.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]

**Comment by Sweenus** [comment]
You need to have at least 1 spell power in the relevant element to heal/deal damage with the skill.
In the case of consecration, you need to equip paladin armor, or a wand with healing power.

@Snautke your issue is different. Please try using the latest version of Simply Skills. If the issue still persists, please create a separate ticket with a full crashlog.
